[2025-10-07T16:06:33.730+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: dag1.test_hello manual__2025-10-07T16:06:33.132498+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
